***Импорт NumPy***

In [2]:
import numpy as np

In [26]:
a = np.array([1, 2, 3]) #преобразовали обычный список в np массив
print(type(a))
b = np.zeros(6) #создали массив с 3 нуоями
c = np.ones((3,4))  #создали матрицу с 3 строками и 4 столбцами, заполненную единицами
d = np.arange(20, 31, 2) # Создали массив от 20 до 31 (не включительно) с шагом 2
print(b)
print(c)
print(d)
print(c.shape) #размерность матрицы
print(c.dtype) #тип данных матрицы
print(d[0])
print(d[1:3])
print(d[::2]) #На всю область массива через один элемент
print(b + d) # сумма 0 и элемента из d равна элементу d
print(b * d) #Умножая каждый элемент массива d на 0 мы получаем массив 0
print(d / b) #Деление на 0 приводит не к ошибке, а к бесконечности (и предупреждению)
print(d.mean()) #Среднее значение массив d

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[20 22 24 26 28 30]
(3, 4)
float64
20
[22 24]
[20 24 28]
[20. 22. 24. 26. 28. 30.]
[0. 0. 0. 0. 0. 0.]
[inf inf inf inf inf inf]
25.0


C:\Users\-\AppData\Local\Temp\ipykernel_32460\2821680532.py:16: RuntimeWarning: divide by zero encountered in divide
  print(d / b) #Деление на 0 приводит не к ошибке, а к бесконечности (и предупреждению)
